# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

# command to install dependencies
install: pip install -r requirements.txt

# before_script: flake8 app tests

# command to run tests, e.g. python setup.py test
script: python setup.py test
